/*******************************************************************************
 * Copyright (c) 2017 I3S laboratory and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     I3S laboratory - initial API and implementation
 *******************************************************************************/
/*
* generated by Xtext
*/
package org.eclipse.gemoc.moccml.mapping.xtext.ui.labeling;


import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.gemoc.moccml.mapping.moccml_mapping.ECLExpression;
import org.eclipse.gemoc.moccml.mapping.moccml_mapping.ECLRelation;
import org.eclipse.gemoc.moccml.mapping.moccml_mapping.EventLiteralExp;
import org.eclipse.gemoc.moccml.mapping.moccml_mapping.EventType;
import org.eclipse.ocl.xtext.completeocl.ui.labeling.CompleteOCLLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class EclLabelProvider extends CompleteOCLLabelProvider {

	@Inject
	public EclLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}


	//Labels and icons can be computed like this:
	
	String text(ECLRelation r) {
	  return r.getType().getName();
	}
	 
    String image(ECLRelation r) {
      return "/org.eclipse.gemoc.moccml.mapping.xtext.ui/icons/relation_small.gif";
    }
    
    String text(EventType e) {
  	  return e.getName();
  	}
  	 
	String image(EventType r) {
	  return "/org.eclipse.gemoc.moccml.mapping.xtext.ui/icons/clock_small.gif";
	}
	
	String text(EventLiteralExp e) {
	  	  return e.getValue().toString();
	}
	
	String image(EventLiteralExp e) {
	  	  return "/org.eclipse.gemoc.moccml.mapping.xtext.ui/icons/clock_small.gif";
	}
	  	 
	String text(ECLExpression e) {
		  return e.getType().getName();
		}
		 
    String image(ECLExpression e) {
      return "/org.eclipse.gemoc.moccml.mapping.xtext.ui/icons/equation_small.gif";
    }
	
	
}
