/*
 * generated by Xtext 2.31.0
 */
package org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext.parser.antlr.internal.InternalFSMDslParser;
import org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext.services.FSMDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FSMDslParser extends AbstractAntlrParser {

	@Inject
	private FSMDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFSMDslParser createParser(XtextTokenStream stream) {
		return new InternalFSMDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "StateMachineDefinition";
	}

	public FSMDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FSMDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
