/*
 * generated by Xtext 2.31.0
 */
package org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext.fsmdsl.ui.internal.FsmdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FSMDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(FsmdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		FsmdslActivator activator = FsmdslActivator.getInstance();
		return activator != null ? activator.getInjector(FsmdslActivator.ORG_ECLIPSE_GEMOC_MOCCML_CONSTRAINT_FSMKERNEL_MODEL_XTEXT_FSMDSL) : null;
	}

}
