/*******************************************************************************
 * Copyright (c) 2017 I3S laboratory and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     I3S laboratory - initial API and implementation
 *******************************************************************************/
/*
* generated by Xtext
*/
package org.eclipse.gemoc.moccml.mapping.xtext.ui.outline;

import org.eclipse.ocl.xtext.completeocl.ui.outline.CompleteOCLOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class EclOutlineTreeProvider extends CompleteOCLOutlineTreeProvider {
	
}
