/*
 * generated by Xtext 2.31.0
 */
package org.eclipse.gemoc.moccml.constraint.ccslmocc.model.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.gemoc.moccml.constraint.ccslmocc.model.xtext.mocdsl.ui.internal.MocdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MoCDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MocdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MocdslActivator activator = MocdslActivator.getInstance();
		return activator != null ? activator.getInjector(MocdslActivator.ORG_ECLIPSE_GEMOC_MOCCML_CONSTRAINT_CCSLMOCC_MODEL_XTEXT_MOCDSL) : null;
	}

}
