/*
 * generated by Xtext 2.31.0
 */
package org.eclipse.gemoc.moccml.constraint.ccslmocc.model.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class MoCDslIdeModule extends AbstractMoCDslIdeModule {
}
