/*******************************************************************************
 * Copyright (c) 2017 I3S laboratory and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     I3S laboratory - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.eclipse.gemoc.moccml.mapping.xtext.ui;

import org.eclipse.gemoc.moccml.mapping.xtext.ui.internal.EclActivator;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EclUiModule extends org.eclipse.gemoc.moccml.mapping.xtext.ui.AbstractEclUiModule {
	
	public static final String EDITOR_ID = EclActivator.ORG_ECLIPSE_GEMOC_MOCCML_MAPPING_XTEXT_ECL;

	public EclUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
