/*******************************************************************************
 * Copyright (c) 2017 I3S laboratory and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     I3S laboratory - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.eclipse.gemoc.moccml.mapping.xtext.scoping;

import org.eclipse.ocl.xtext.completeocl.scoping.CompleteOCLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class EclScopeProvider extends CompleteOCLScopeProvider{//AbstractDeclarativeScopeProvider {
	
//	//CompleteOCLScopeProvider delegator = new CompleteOCLScopeProvider();
//	
//	@Override
//	public IScope getScope(EObject context, EReference reference) {
////		if (context instanceof Relation | context instanceof ECLExpression){
////			return super.getScope(context, reference);
////		}
////		else{
//			return super.getScope(context, reference);
////		}
//		
//	}
}
