/*
 * generated by Xtext 2.31.0
 */
package org.eclipse.gemoc.moccml.constraint.ccslmocc.model.xtext.scoping;

import org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext.scoping.FSMDslScopeProvider;

public abstract class AbstractMoCDslScopeProvider extends FSMDslScopeProvider {
}
