/*
 * generated by Xtext 2.31.0
 */
package org.eclipse.gemoc.moccml.constraint.ccslmocc.model.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.gemoc.moccml.constraint.ccslmocc.model.xtext.parser.antlr.internal.InternalMoCDslParser;
import org.eclipse.gemoc.moccml.constraint.ccslmocc.model.xtext.services.MoCDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MoCDslParser extends AbstractAntlrParser {

	@Inject
	private MoCDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMoCDslParser createParser(XtextTokenStream stream) {
		return new InternalMoCDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "StateRelationBasedLibrary";
	}

	public MoCDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MoCDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
