/*
 * generated by Xtext 2.31.0
 */
package org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext.FSMDslRuntimeModule;
import org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext.FSMDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FSMDslIdeSetup extends FSMDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FSMDslRuntimeModule(), new FSMDslIdeModule()));
	}
	
}
