/*
 * generated by Xtext 2.31.0
 */
package org.eclipse.gemoc.moccml.constraint.fsmkernel.model.xtext.scoping;

import fr.inria.aoste.timesquare.ccslkernel.library.xtext.scoping.CCSLLibraryScopeProvider;

public abstract class AbstractFSMDslScopeProvider extends CCSLLibraryScopeProvider {
}
